
        
create table acl_sid(
	id bigint generated by default as identity(start with 100) not null primary key,
	principal boolean not null,
	sid varchar_ignorecase(100) not null,
	constraint unique_uk_1 unique(sid,principal)
);

create table acl_class(
	id bigint generated by default as identity(start with 100) not null primary key,
	class varchar_ignorecase(100) not null,
	constraint unique_uk_2 unique(class)
);

create table acl_object_identity(
	id bigint generated by default as identity(start with 100) not null primary key,
	object_id_class bigint not null,
	object_id_identity bigint not null,
	parent_object bigint,
	owner_sid bigint,
	entries_inheriting boolean not null,
	constraint unique_uk_3 unique(object_id_class,object_id_identity),
	constraint foreign_fk_1 foreign key(parent_object)references acl_object_identity(id),
	constraint foreign_fk_2 foreign key(object_id_class)references acl_class(id),
	constraint foreign_fk_3 foreign key(owner_sid)references acl_sid(id)
);

create table acl_entry(
	id bigint generated by default as identity(start with 100) not null primary key,
	acl_object_identity bigint not null,
	ace_order int not null,
	sid bigint not null,
	mask integer not null,
	granting boolean not null,
	audit_success boolean not null,
	audit_failure boolean not null,
	constraint unique_uk_4 unique(acl_object_identity,ace_order),
	constraint foreign_fk_4 foreign key(acl_object_identity) references acl_object_identity(id),
	constraint foreign_fk_5 foreign key(sid) references acl_sid(id)
);



insert into acl_sid(id,principal,sid) values (1,true,'kbowersox');
insert into acl_sid(id,principal,sid) values (2,true,'jadoe');
insert into acl_sid(id,principal,sid) values (3,false,'ROLE_ADMIN');
insert into acl_sid(id,principal,sid) values (4,false,'ROLE_USER');

insert into acl_class(id,class)values(1,'com.oreilly.security.domain.entities.Appointment');

insert into acl_object_identity(id,object_id_identity,object_id_class,parent_object,owner_sid,entries_inheriting)
	values (1,1,1,null,1,false);

insert into acl_object_identity(id,object_id_identity,object_id_class,parent_object,owner_sid,entries_inheriting)
	values (2,2,1,null,2,false);
	
insert into acl_entry(acl_object_identity,ace_order,sid,mask,granting,audit_success,audit_failure)
	values(1,1,1,1,true,true,true);

insert into acl_entry(acl_object_identity,ace_order,sid,mask,granting,audit_success,audit_failure)
	values(1,2,1,16,true,true,true);

insert into acl_entry(acl_object_identity,ace_order,sid,mask,granting,audit_success,audit_failure)
	values(2,1,2,1,true,true,true);

	
	
	

























