drop table users if exists;

create table users(
		username varchar_ignorecase(50) not null primary key,
		password varchar_ignorecase(250) not null,
		enabled boolean not null
	);
	
	create table authorities (
    	username varchar(256) not null,
    	authority varchar(256) not null,
    	constraint fk_authorities_users
        foreign key(username) references users(username)
	);
	
	create unique index ix_auth_username on authorities (username,authority);
	
create table groups (
	id bigint generated by default as identity(start with 0) primary key,
	group_name varchar_ignorecase(50) not null
);

create table group_authorities (
	group_id bigint not null,
	authority varchar(50) not null,
	constraint fk_group_authorities_group foreign key(group_id) references groups(id)
);

create table group_members (
	id bigint generated by default as identity(start with 0) primary key,
	username varchar(50) not null,
	group_id bigint not null,
	constraint fk_group_members_group foreign key(group_id) references groups(id)
);
insert into users(username, password, enabled) values ('nuser', '{bcrypt}$2a$10$FvozkOSRSTGKeRmFTSaw6eaSyMSSxz0pfzBc4FTtxftg7KQ9r9r6e', 1);
insert into users(username, password, enabled) values ('auser', '{bcrypt}$2a$12$FIp58ZtVaSksbursdII0cOaBm98s91DRTqnzRdjrG07q/ukPrgSWq', 1);

insert into groups(id, group_name) values(1, 'Admins');
insert into group_authorities(group_id, authority) values (1, 'ROLE_USER');
insert into group_authorities(group_id, authority) values (1, 'ROLE_ADMIN');
insert into group_members(id, username, group_id) values(1, 'nuser', 1);
insert into group_members(id, username, group_id) values(2, 'auser', 1);